src/View.php, src/View/smartyView.php
#4 Add Response status for renderJSON
=> Add response status to renderJSON

src/View/interfaceView.php
=> add status in interface

src/View/DefaultView.php
Add fetching and change defaultConfig, to default
=> Changing default View

src/Router/Response.php
Adding json function, and changing header to headers
=> json and headers

src/Router.php
=> adjusted regexp and link generation

src/Router.php
=> Updated variables for router merger

src/Router.php
=> Routers merger fix

src/Router.php
=> Tweaked router array sort method

src/Router.php
=> Fix Linux slash

.travis.yml, README.md, composer.json, phpunit.xml, tests/Bootstrap.php, tests/ConfigTest.php, tests/ResponseTest.php, tests/RouterTest.php, tests/RunTest.php
| Branch?       | test_enhancement
- Organize the ```tests``` folder and related Test classes.
- Using the stable PHPUnit version and the PHPUnit namespace is class-based by default.
- In ```README.md```, the PHP version should be ```>=7.0``` in the ```Requirements``` section.
=> Test enhancement

src/Router.php
=> sVars reset each loop

docs/extensions/Config.md, src/Asset/Assetic.php, src/Config.php, src/Functions.php, src/Loader.php, src/Messages.php, src/Model.php, src/Router.php, src/Router/Response.php, src/Session.php, src/Token.php, src/View.php, src/View/TwigView.php, tests/ConfigTest.php, tests/RouterTest.php
| Fixed Issue | #20 
Replaces array() with []
=> Resolved #20, Replaces array() with []

src/Asset/Assetic.php, src/Config.php, src/Loader.php, src/Router.php, src/Router/Response.php, src/Session.php
| Fixed Issue | #23 
No need for underscores for private methods
=> Resolved #23, No need for underscores for private methods

src/Debug.php, src/Loader.php, src/Router.php
| Fixed Issue | #25 
Add prototype debug
=> Resolved #25, prototype debug in header

src/Asset/Assetic.php, src/Asset/Exceptions/AsseticException.php, src/Loader.php, src/Loader/Exceptions/LoaderException.php, src/Router.php, src/Router/Exceptions/InvalidArgumentException.php, src/Router/Exceptions/RouterException.php, src/Router/Exceptions/RuntimeException.php, src/View.php, src/View/DefaultView.php, src/View/Exceptions/ViewException.php, src/View/SmartyView.php, src/View/TwigView.php, src/View/ViewInterface.php
| Fixed Issue | #28 
Add new Exceptions
=> Resolved #28, Extend Exception

src/Asset/Exceptions/AsseticException.php, src/Loader/Exceptions/LoaderException.php, src/Router/Exceptions/InvalidArgumentException.php, src/Router/Exceptions/RouterException.php, src/Router/Exceptions/RuntimeException.php, src/View/Exceptions/ViewException.php
=> Resolved #31, Exception not found

.travis.yml, src/Config.php, src/Loader.php, src/Messages.php, src/Router.php, src/Session.php, src/Token.php, src/View.php, src/View/DefaultView.php, src/View/SmartyView.php
| Branch?       | features
| Fixed Issue | #22 
=> Try to add this feature for issue #22

tests/SessionTest.php
- It's related to issue #40.
- Add the session tests.
=> Add session tests

src/Session.php, src/Token.php
| Fixed Issue | #46 #98 #99 #100 
=> Update Token.php Session.php 

tests/Bootstrap.php, tests/RouterTest.php, tests/SessionTest.php
| Branch?       | more_tests
| Fixed Issue | issue #40 
- Add `Functions` class test.
=> Add Functions test

src/Loader.php, src/Router/Response.php
=> Fix some Scrutinizer errors

composer.json, tests/FunctionsTest.php
| Fixed Issue | It's related to issue #40, and it's about accomplishing `Functions` class test.
=> Complete Functions tests

.gitignore, src/Router.php
=> Fix some errors from Scrutinizer and update to gitignore

.gitignore, composer.json, src/Config.php, src/Core.php, src/Loader.php, src/Router.php, src/Router/Response.php, src/Session.php, tests/Controller/Sub/SubTestController.php, tests/Controller/TestController.php, tests/FunctionsTest.php, tests/LoaderTest.php
=> Merged master to v4.0

.gitignore, composer.json, src/Config.php, src/Core.php, src/Loader.php, src/Router.php, src/Router/Response.php, src/Session.php, tests/Controller/Sub/SubTestController.php, tests/Controller/TestController.php, tests/FunctionsTest.php, tests/LoaderTest.php
=> marge v.4.0 to V4.1

src/Loader.php
=> Fix wrong LoaderException message on Loader::autoload()

tests/Bootstrap.php, tests/TokenTest.php
| Fixed Issue | It's related to issue #40, and this issue is for accomplishing `Token` class tests.
=> Cmplete Token class tests

src/Router/Response.php
Reverts dframe/dframe#107
It's force string to int even it is string for example if you have "0001" result will be display as "1"
=> Revert "Update Response.php"

composer.json, src/View/SmartyView.php, src/View/TwigView.php
| Deprecations? | yes
| Fixed Issue | -
Update Twig to 3.x line
=> Update Twig to 3.x
